#!/usr/bin/env python3
"""Emit the small support tables: Lipschitz + resolution-transfer.

Inputs:
  results/lipschitz.csv
  results/resolution_transfer.csv

Outputs:
  results/lipschitz.tex
  results/resolution_transfer.tex
"""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# ── Lipschitz table ──────────────────────────────────────────────────────────
LIPS_CSV = ROOT / "tables" / "lipschitz.csv"
LIPS_TEX = ROOT / "tables" / "lipschitz.tex"

with LIPS_CSV.open() as f:
    rows = list(csv.DictReader(f))

# Group by (model_kind, params) → dict of T → mean.
# Distinguish SpectraNet w=32+residual (params=2124166) from SpectraNet w=48 plain
# (params=4776006), the FNO baseline, and the Transformer baseline.
PARAMS_TO_LABEL = {
    2124166: "SpectraNet $w{=}32$ + residual",
    4776006: "SpectraNet $w{=}48$ plain",
    4749377: "FNO",
    4381441: "Transformer (NSL)",
}

# The Semigroup-Consistency-Loss checkpoint has the same param count as the
# w=32 + residual baseline, but its rows came in second (after the first four
# blocks in the original run). The CSV order is:
#   [W32R T=1, W32R T=10, W48 T=1, W48 T=10, FNO T=1, Tfm T=1,    ← first job
#    +SCL T=1, +SCL T=10, FNO T=10, Tfm T=10]                      ← second job
# So rows 7,8 (0-indexed 6,7) are the Semigroup-Consistency Loss variant.

# Build a dict keyed by (label, T)
table = {}
for i, r in enumerate(rows):
    p   = int(r["params"])
    T   = int(r["rollout_T"])
    Lh  = float(r["L_hat_mean"])
    p95 = float(r["L_hat_p95"])
    label = PARAMS_TO_LABEL[p]
    if p == 2124166 and i >= 6:
        label = "SpectraNet (multi-res $+$ KAN head, $+$ SCL)"
    table[(label, T)] = (Lh, p95)

ORDER = [
    "Transformer (NSL)",
    "FNO",
    "SpectraNet $w{=}48$ plain",
    "SpectraNet $w{=}32$ + residual",
    "SpectraNet (multi-res $+$ KAN head, $+$ SCL)",
]

with LIPS_TEX.open("w") as f:
    f.write("% Auto-generated by scripts/figures/make_aux_tables.py — do not edit by hand.\n")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Empirical Lipschitz constant $\\widehat{L} = \\sup_{u,\\varepsilon}"
            "\\|f(u{+}\\varepsilon) - f(u)\\| / \\|\\varepsilon\\|$ at single-step ($T{=}1$) "
            "and full-rollout ($T{=}10$), estimated from 100 Gaussian perturbations of size "
            "$10^{-3}$ on 100 test inputs. The residual-target operators have $\\widehat{L}$ "
            "inflated by the $+\\,1$ identity term; per Lemma~\\ref{lemma:residual-stab}, "
            "$\\widehat{L}$ is not the load-bearing stability quantity for these architectures. "
            "FNO's $\\widehat{L}{=}1.84{>}1$ predicts the catastrophic divergence of "
            "Sec.~\\ref{sec:results:longhorizon}.}\n")
    f.write("\\label{tab:lipschitz}\n")
    f.write("\\begin{tabular}{lrrr}\n\\toprule\n")
    f.write("Model & $\\widehat{L}(T{=}1)$ mean & $\\widehat{L}(T{=}10)$ mean & p95 ($T{=}1$) \\\\\n\\midrule\n")
    for label in ORDER:
        T1  = table.get((label, 1),  (None, None))
        T10 = table.get((label, 10), (None, None))
        L1  = f"{T1[0]:.2f}"  if T1[0]  is not None else "—"
        L10 = f"{T10[0]:.2f}" if T10[0] is not None else "—"
        p95 = f"{T1[1]:.2f}"  if T1[1]  is not None else "—"
        f.write(f"{label} & {L1} & {L10} & {p95} \\\\\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

print(f"wrote {LIPS_TEX}")

# ── Resolution-transfer table ────────────────────────────────────────────────
RES_CSV = ROOT / "tables" / "resolution_transfer.csv"
RES_TEX = ROOT / "tables" / "resolution_transfer.tex"

with RES_CSV.open() as f:
    rrows = list(csv.DictReader(f))

# Group rows by (model, params). Each (model, params) block has up to 4 rows:
# bilinear native + bilinear transfer + spectral_zeropad native + spectral_zeropad transfer.
# We discriminate SpectraNet head variants by parameter count: 2,124,166 =
# decorated multi-resolution + KAN head (the variant tested in ablation E7);
# 2,040,705 = canonical SpectraNet with the two-layer 1x1 MLP output head.
# FNO at 4,749,377 is the spectral baseline.

# (display_label, model_kind, params)
GROUPS = [
    ("SpectraNet (multi-res $+$ KAN head)", "ar2d", 2_124_166),
    ("\\textbf{SpectraNet} (canonical, MLP head)", "ar2d", 2_040_705),
    ("FNO", "fno", 4_749_377),
]

with RES_TEX.open("w") as f:
    f.write("% Auto-generated by scripts/figures/make_aux_tables.py — do not edit by hand.\n")
    f.write("\\begin{table}[t]\n\\centering\n")
    f.write("\\caption{Zero-shot resolution transfer $64^2 \\!\\to\\! 128^2$ via spectral "
            "zero-padding of the test inputs. Native $L^2$ is the model's own $64^2$ "
            "result. Ratio = test-$L^2$ at $128^2$ / native-$64^2$. The spectral "
            "convolution layer is resolution-invariant by construction "
            "(Prop.~\\ref{prop:res-inv}); FNO's purely spectral output projection inherits "
            "this cleanly. The decorated SpectraNet variant (multi-resolution $+$ KAN "
            "output head, top block) and the canonical SpectraNet (two-layer "
            "$1{\\times}1$ MLP head, middle block) both incur a "
            "$\\sim\\!2.0\\!-\\!2.2\\times$ transfer-ratio "
            "degradation: the head decoration is \\emph{not} the source of the "
            "resolution-transfer gap. The actual source is discussed in "
            "Sec.~\\ref{sec:results:resolution}.}\n")
    f.write("\\label{tab:resolution}\n")
    f.write("\\begin{tabular}{llrrr}\n\\toprule\n")
    f.write("Model & Upsample & Native $L^2$ ($64^2$) & Transfer $L^2$ ($128^2$) & Ratio \\\\\n\\midrule\n")
    for gi, (label, m, p) in enumerate(GROUPS):
        block = [r for r in rrows if r["model"] == m and int(r["params"]) == p]
        for upsample in ["bilinear", "spectral_zeropad"]:
            natives = [r for r in block
                       if abs(float(r["transfer_native_ratio"]) - 1.0) < 1e-6
                       and r["upsample"] == upsample]
            transfers = [r for r in block
                         if abs(float(r["transfer_native_ratio"]) - 1.0) > 1e-6
                         and r["upsample"] == upsample]
            if not natives or not transfers:
                continue
            native_L2 = float(natives[0]["mean_L2"])
            transfer_L2 = float(transfers[0]["mean_L2"])
            ratio = transfer_L2 / native_L2
            up_label = upsample.replace("_", "\\_")
            f.write(f"{label} & {up_label} & {native_L2:.4f} & {transfer_L2:.4f} & "
                    f"{ratio:.2f}$\\times$ \\\\\n")
        if gi != len(GROUPS) - 1:
            f.write("\\midrule\n")
    f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

print(f"wrote {RES_TEX}")
