#!/usr/bin/env python3
"""Emit the cross-PDE comparison table.

Pivots results/cross_pde.csv (one row per (dataset, arch)) into a single
LaTeX table where each dataset is one row with both architectures' columns.

Inputs:
  results/cross_pde.csv

Outputs:
  results/cross_pde.tex

Usage:
  python3 scripts/figures/make_cross_pde_table.py

Verification (L18.3 acceptance):
  Generated table should match the inlined hand-edited table in
  paper/sections/appendix_cross_pde.tex up to whitespace.

Notes:
  - Params are emitted as "X.YY M" using the canonical PyTorch convention
    (sum_p p.numel(), one complex param = one element). Stale 3.93M-from-
    complex-doubled count is rejected by an assertion.
  - Row ordering matches the appendix's narrative arc:
      headline (NS ν=1e-5) → smoothest (ν=1e-3) → intermediate (ν=1e-4)
      → SW → DR → AM (DR/AM appended when their rows land).
  - The `note` column in cross_pde.csv is consulted only to flag the
    headline row (multi-seed) vs. single-seed transfer rows. The convention
    used here: a row whose note contains "headline" is bolded with the
    "(turbulent, headline)" label suffix; other rows get a short
    parenthetical regime label looked up in REGIME_LABELS.
"""
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IN_CSV  = ROOT / "tables" / "cross_pde.csv"
OUT_TEX = ROOT / "tables" / "cross_pde.tex"

# Display-name + regime-label per dataset key in the CSV.
DATASET_LABELS = {
    "NS_nu1e-5":      ("NS $\\nu\\!=\\!10^{-5}$",      "turbulent, headline"),
    "NS_nu1e-3":      ("NS $\\nu\\!=\\!10^{-3}$",      "smooth"),
    "NS_nu1e-4":      ("NS $\\nu\\!=\\!10^{-4}$",      "intermediate"),
    "ShallowWater_2D": ("Shallow-Water 2D",            None),
    "PDEBench_DR":    ("PDEBench Diffusion-Reaction",  None),
    "TheWell_AM":     ("The Well Active-Matter",       None),
}

# Canonical row order (datasets appear here in narrative-arc order; missing
# datasets are silently skipped, so the table grows as new rows land).
ROW_ORDER = [
    "NS_nu1e-5",
    "NS_nu1e-3",
    "NS_nu1e-4",
    "ShallowWater_2D",
    "PDEBench_DR",
    "TheWell_AM",
]

ARCH_AR2D_LABELS = ("spectranet_canonical_linear_head", "ar2d_w32_resi_2step_E6")
ARCH_FNO  = "fno_n64_m12"


def fmt_params(p_int: int) -> str:
    # Canonical PyTorch convention check: catch the legacy complex-doubled count
    # (3,926,406) that survived Session 12's canonicalization in some places —
    # see RESEARCH_STATE.md §18.A row 4.
    assert p_int != 3_926_406, (
        "Detected legacy complex-doubled SpectraNet param count (3,926,406). "
        "Use the canonical 2,124,166 (decorated head) or 2,040,705 (canonical) "
        "instead — see RESEARCH_STATE.md. Update cross_pde.csv before regenerating."
    )
    return f"{p_int / 1e6:.2f}\\,\\text{{M}}"


def fmt_l2(l2: float) -> str:
    # Match the precision used in the existing hand-edited table:
    # NS ν=1e-5 / ν=1e-3 / SW / DR: 4 decimals; ν=1e-4 / AM: 5 decimals.
    # Rule: if |l2| < 0.01, use 5 decimals; otherwise 4. This keeps the AM
    # row consistent (both 0.00170 and 0.00149 displayed with 5 decimals).
    min_decimals = 5 if abs(l2) < 0.01 else 4
    s = f"{l2:.5f}".rstrip("0")
    if s.endswith("."):
        s += "0"
    int_part, frac_part = s.split(".")
    if len(frac_part) < min_decimals:
        frac_part = frac_part.ljust(min_decimals, "0")
    return f"{int_part}.{frac_part}"


def main() -> None:
    with IN_CSV.open() as f:
        rows = list(csv.DictReader(f))

    # Pivot: dataset → {arch: row}
    by_dataset: dict[str, dict[str, dict]] = {}
    for r in rows:
        by_dataset.setdefault(r["dataset"], {})[r["arch"]] = r

    with OUT_TEX.open("w") as f:
        f.write("% Auto-generated by scripts/figures/make_cross_pde_table.py — "
                "do not edit by hand.\n")
        f.write("\\begin{table}[h]\n\\centering\n")
        f.write("\\caption{SpectraNet vs.\\ canonical FNO on additional PDE/regime "
                "combinations, native-trained under the headline protocol. SpectraNet wins "
                "at smaller parameter count on $5$ of $6$ rows; the $6^{\\text{th}}$ "
                "(TheWell active matter) is the regime where the rollout-error compounding "
                "term is structurally suppressed --- see \\Cref{appendix:cross-pde} for the "
                "regime-controlled discussion. The NS~$\\nu\\!=\\!10^{-5}$ row uses the "
                "canonical SpectraNet (two-layer $1{\\times}1$ MLP output head, "
                "$2.04\\,\\text{M}$ params); the remaining five rows used checkpoints with "
                "the decorated multi-resolution $+$ KAN output head ($2.12\\,\\text{M}$ "
                "params), which the output-head decoration ablation in "
                "\\Cref{sec:ablations:micro} shows is statistically indistinguishable from "
                "the canonical two-layer MLP head at the headline operating point. Bolded "
                "entries indicate the winning architecture per row.}\n")
        f.write("\\label{tab:cross_pde}\n")
        f.write("\\begin{tabular}{lrrrr}\n\\toprule\n")
        f.write("Dataset & SpectraNet params & SpectraNet $L^2$ & FNO params & FNO $L^2$ \\\\\n")
        f.write("\\midrule\n")

        for ds_key in ROW_ORDER:
            if ds_key not in by_dataset:
                continue
            block = by_dataset[ds_key]
            ar2d = next((block[a] for a in ARCH_AR2D_LABELS if a in block), None)
            if ar2d is None or ARCH_FNO not in block:
                # Incomplete row — skip silently (e.g. only one of the two
                # archs has finished training).
                continue
            fno  = block[ARCH_FNO]
            label, regime = DATASET_LABELS[ds_key]
            if regime is not None:
                label = f"{label} ({regime})"
            ar2d_p  = fmt_params(int(ar2d["params"]))
            fno_p   = fmt_params(int(fno["params"]))
            ar2d_l2_v = float(ar2d["test_l2"])
            fno_l2_v  = float(fno["test_l2"])
            ar2d_l2 = fmt_l2(ar2d_l2_v)
            fno_l2  = fmt_l2(fno_l2_v)
            # Bold the winner per row (SpectraNet wins every row except TheWell_AM).
            if ar2d_l2_v <= fno_l2_v:
                ar2d_cell = f"$\\mathbf{{{ar2d_l2}}}$"
                fno_cell  = f"${fno_l2}$"
            else:
                ar2d_cell = f"${ar2d_l2}$"
                fno_cell  = f"$\\mathbf{{{fno_l2}}}$"
            f.write(f"{label} & ${ar2d_p}$ & {ar2d_cell} "
                    f"& ${fno_p}$ & {fno_cell} \\\\\n")

        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")

    print(f"wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
